plugins {
	id 'fabric-loom' version '1.10-SNAPSHOT'
	id 'maven-publish'
}

version = project.mod_version + "+" + project.minecraft_version + "-refabricated"
group = project.mod_group_id

base {
	archivesName = project.mod_id
}

repositories {
	// Add repositories to retrieve artifacts from in here.
	// You should only use this when depending on other mods because
	// Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
	// See https://docs.gradle.org/current/userguide/declaring_repositories.html
	// for more information about repositories.
	maven {
		name = 'ParchmentMC'
		url = 'https://maven.parchmentmc.org'
	}
	maven {
		// location of the maven that hosts JEI files since January 2023
		name = "Jared's maven"
		url = "https://maven.blamejared.com/"
	}
	maven {
		// location of a maven mirror for JEI files, as a fallback
		name = "ModMaven"
		url = "https://modmaven.dev"
	}
	maven {
		name = "Fuzs Mod Resources"
		url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
	}
	maven { url = "https://maven.terraformersmc.com/" } // Mod Menu, EMI
	maven { url 'https://repo.sleeping.town/' } // Kaleido Config
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	   mappings loom.layered() {
         officialMojangMappings()
         parchment("org.parchmentmc.data:parchment-${project.parchment_minecraft_version}:${project.parchment_mappings_version}@zip")
     }
	modImplementation("net.fabricmc:fabric-loader:0.16.14")

	// Fabric API. This is technically optional, but you probably want it anyway.
	modImplementation("net.fabricmc.fabric-api:fabric-api:0.116.1+${project.minecraft_version}")

    modCompileOnlyApi("mezz.jei:jei-${jei_minecraft_version}-fabric-api:${jei_version}")
	modRuntimeOnly("mezz.jei:jei-${jei_minecraft_version}-fabric:${jei_version}")
	modImplementation("com.terraformersmc:modmenu:11.0.3")
	implementation(include( 'folk.sisby:kaleido-config:0.3.3+1.3.2'))
}

processResources {
	var replaceProperties = [
			"mod_id": mod_id,
			"mod_name": mod_name + " Refabricated",
			"mod_description": mod_description + " An unofficial Fabric port.",
			"mod_authors": "cassiancc",
			"mod_credits": mod_authors,
			"mod_license": mod_license,
			"minecraft_version": minecraft_version,
			"mod_version": version
	]
	// setting them as input
	inputs.properties replaceProperties

	filesMatching("fabric.mod.json") {
		expand replaceProperties + [project: project]
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}

loom {
	accessWidenerPath = file("src/main/resources/${mod_id}.accesswidener")
}

sourceSets.main.resources {
	srcDirs += 'src/generated/resources'
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.mod_id
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}